# Menus
menu:
  主页: .
  归档: archives
  分类: categories
  标签: tags
  关于: about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
#        avatar: css/images/avatar.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: 枫叶上的毛蟲
        author_title: ""
        location: 中国 广东
        follow: https://github.com/cpaladin/
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: https://github.com/cpaladin/
#        twitter: /
#        facebook: /
#        dribbble: /
        weixin: /
        rss: /

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    swiftype: false # enter swiftype install key here
    baidu: true # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: #hexo-theme-icarus # enter disqus shortname here
    duoshuo: blogwei # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: jiathis # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    fancybox: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: 96ec8431956f5b7debdcd2f1bc9f4c70 # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
        逗比邦邦的博客: http://shuovr.cn
